### ISSUE TITLE
Fix NFT processing to allow NFTs of any type

### ISSUE THREAD

**Issue by pavitthrap** [hirosystems/stacks-subnets#123]
Right now, the value of an NFT is constrained to be type uint, as we are currently only supporting SIP-009 compatible NFTs. 

In the future, we may want to make it such that it can be any Clarity value. 
Implementation detail: the id field of the struct `DepositNftOp` should be Value instead of uint.

**Comment by gregorycoppola** [comment]
All the other types are enumerable so might as well be `uint`.

**Comment by saralab** [comment]
We will only handle uints
