### ISSUE TITLE
Support withdrawals of conflicting NFT assets

### ISSUE THREAD

**Issue by pavitthrap** [hirosystems/stacks-subnets#126]
With the current implementation, if a user deposits an NFT into the hyperchain that already exists on the hyperchain, the mint of that NFT will fail on the hyperchain. The user will then not have an option to withdraw that NFT from the L1 contract. 

A possible solution for this conflict is to issue a withdrawal on a failed mint. 
This withdrawal issuance could be done in the case that a stx/fungible token mint fails too.

**Comment by kantai** [comment]
Related to https://github.com/hirosystems/stacks-subnets/issues/146

**Comment by obycode** [comment]
As a starting place for this issue, you can check out `process_deposit_ft_ops`/`process_deposit_nft_ops` in src/chainstate/stacks/db/blocks.rs. This is where the deposit function is called. The idea is that if that call fails, then the asset gets added directly to the withdrawal tree (see src/clarity_vm/withdrawals.rs).
