### ISSUE TITLE
Add sender validation to block proposal RPC

### ISSUE THREAD

**Issue by kantai** [hirosystems/stacks-subnets#135]
The block proposal RPC implemented in #134 does not currently validate that the proposal submitted was created by the multi-party leader. This is necessary to prevent the block proposal interface from being a denial-of-service vector.

In order to implement this:

1. The "leader" will need to be configurable via the node config. I think this should be added as part of the `MultiMiner` variant of the `CommitStrategy` configuration. It then needs to be added to the `ConnectionOptions` object in order to be available to the RPC implementation.
2. The block proposal RPC endpoint should be altered to accept a `POST`ed stream of JSON objects (as opposed to just a single JSON object now) -- the first JSON object should be a hex encoded signature, the second JSON object should be a hex encoded hash of the `BlockProposal`JSON string, and then the third JSON object would be the `BlockProposal` object.
3. The RPC endpoint should validate that the JSON `BlockProposal` matches the supplied hash, and then check that the signature matches the leader's public key. All this must happen _before_ the `BlockProposal` is parsed via `serde_json`.

**Comment by saralab** [comment]
@kantai's Notes Implementation so far: 
- Block assembler[Leader|Proposer] proposes to a pool of follower nodes[Validators]
- Follower nodes validate that block and sign it 
- Submit the block commit to the HC contract on L1

Follow up work @gregorycoppola : 
- Validators shouldn't be evaluating blocks that aren't from the Proposer, this could lead to race conditions 
- Microblock Proposal Interface: Microblocks to work within this framework. After the Leader produces the Anchor block, it is able to produce the microblocks.

**Comment by kantai** [comment]
That's fine @gregorycoppola, if you want to start working on performance baselines for hyperchains, I'd recommend starting here: https://github.com/hirosystems/stacks-hyperchains/issues/130#issuecomment-1189427236

**Comment by gregorycoppola** [comment]
Yes.. I'm going to bring up a system based on the L1 running the `mocknet` config, and then L2 running off of that.

We can try it with 1) no micro-blocks, and 2) many values of N in "wait N seconds before making an anchored block".

**Comment by kantai** [comment]
So, I think this task could be broken up into three smaller tasks and the way to break this up would be the following:

1. Start with adding a signature validation function to the `Proposal` struct (or a wrapper struct like `SignedProposal`). This should be a signature field, which is the signature over a hash of the serialization of the `Proposal` struct (serialization could just use with the default serde::json serialization).

https://github.com/hirosystems/stacks-subnets/blob/master/src/chainstate/stacks/miner.rs#L142

The signature scheme should be secp256k1 (like the returned signature from the validator), so the validation method would look something like:

```
/// Perform the secp256k1 signature validation, recovering the public key used to sign
pub fn recover_signer_pk(&self) -> Result<Secp256k1PublicKey, Error>
```

This would also require adding a corresponding signing function to the proposal struct:

```
/// Sign the whole data structure so that RPC handlers can validate the proposal request was sent by the leader
pub fn sign_for_authentication(&self, signing_key: &Secp256k1PrivateKey) -> Result<SignedProposal, Error>
```

2. Integrate the signing validation into the RPC handler (accepting any signer as valid)

https://github.com/hirosystems/stacks-subnets/blob/master/src/net/rpc.rs#L931

This method should be changed to accept a `SignedProposal` struct, which will mean updating the `http::parse_block_proposal` method as well. The `SignedProposal` struct should be checked with `recover_signer_pk()`, but any returned PublicKey should be accepted.

The leader code will also need to be updated as part of this:

https://github.com/hirosystems/stacks-subnets/blob/master/testnet/stacks-node/src/burnchains/commitment.rs#L367

The `propose_block_to` method either needs to change to accept a `SignedProposal` object _or_ needs to be passed a private key to sign with (the private key should be the same private key that gets passed into the `op_signer` field of `make_commit_tx`).

3. Validate the signer is a member of the signing coalition

The RPC handler needs to be passed an additional argument `allowed_proposers: &[Secp256k1PublicKey]` which is list of public keys whose proposals should be considered. That list will need to come from the node config. Getting that information from the node configuration to the RPC handler requires wiring a lot of structs together: adding a new field to the `ConnectionOptions` struct, and setting that value from the `stacks-node` initialization.

https://github.com/hirosystems/stacks-subnets/blob/master/src/net/connection.rs#L323

The fields of `ConnectionOptions` can be set from here:

https://github.com/hirosystems/stacks-subnets/blob/master/testnet/stacks-node/src/config.rs#L510
