### ISSUE TITLE
Update README.MD for this repo

### ISSUE THREAD

**Issue by kantai** [hirosystems/stacks-subnets#139]
The readme for this repo is entirely `stacks-blockchain` content -- it should be updated to be hyperchains oriented content.

**Comment by LakshmiLavanyaKasturi** [comment]
Hyperchains (Subnet) readme is ready for review on [Notion](https://www.notion.so/hiropbc/Subnet-Readme-md-1fa867fbdeec47b4bde9f93943f09901).
