### ISSUE TITLE
Handle failed deposits gracefully

### ISSUE THREAD

**Issue by pavitthrap** [hirosystems/stacks-subnets#146]
If a deposit fails (i.e. a subnets node is unable to mint a deposited asset on the hyperchain), the node should automatically submit that asset for withdrawal.

Moreover, if the deposit function on the hyperchain fails to mint the right quantity, the effects of that mint should be rolled back, and the asset should be submitted for withdrawal as well. For example, this case would apply if a user tried to deposit 100 fungible tokens, and only 50 were minted.

**Comment by kantai** [comment]
Related to #126

**Comment by jbencin** [comment]
I can fairly easily handle the scenario where the transaction fails completely, and do something similar to #126. I am less sure of what to do in this scenario:

> For example, this case would apply if a user tried to deposit 100 fungible tokens, and only 50 were minted.

Is something like this even possible? I would guess that if something like this is happening, it is an issue with the FT contract itself, and should be fixed there.

**Comment by kantai** [comment]
> Is something like this even possible? I would guess that if something like this is happening, it is an issue with the FT contract itself, and should be fixed there.

Yeah, it's possible, but I agree with you -- this seems like an error in the FT contract and I don't think the subnet should try to do special handling in this case.
