### ISSUE TITLE
refactor deposit functions to improve ease of use

### ISSUE THREAD

**Issue by pavitthrap** [hirosystems/stacks-subnets#151]
Right now we put the onus on the user to specify the contract ID for the asset they are depositing. 
However, we already pre-specify the name of the deposit function (within the subnets asset contract) in a map - it could make sense to store the contract address of the corresponding contract on the subnets in that same map.

**Comment by kantai** [comment]
Is this possible given the way traits work? I think that if a trait needs to be invoked to perform the deposit transfer, the contract needs to be supplied directly as argument (because the implementation of the Clarity trait can't be read from a data map).

**Comment by pavitthrap** [comment]
No, it is not possible with how traits work currently. Traits can't be stored in data maps or variables.
