### ISSUE TITLE
Update blogs to use "subnets" instead of "hyperchains"

### ISSUE THREAD

**Issue by a3slade** [hirosystems/stacks-subnets#161]
Change Hyperchains to Subnets for these two posts:
https://www.hiro.so/blog/introducing-hyperchains-by-hiro
https://www.hiro.so/blog/an-update-on-hyperchains-a-scaling-solution-for-stacks

If the links to those are changed, then update them here:
hirosystems/stacks-subnets/README.md
https://www.youtube.com/watch?v=PFPwuVCGGuI
and wherever else?

**Comment by obycode** [comment]
Looks like these two posts have an added note at the top now:

> Note: hyperchains have been renamed subnets, due to the trademark for "hyperchains" already being registered. [Learn more here](https://www.hiro.so/blog/its-official-hyperchains-are-now-named-subnets).
