### ISSUE TITLE
Create RPC endpoint to retrieve withdrawal info for fungible tokens

### ISSUE THREAD

**Issue by pavitthrap** [hirosystems/stacks-subnets#164]
I noticed that we only have implemented the withdrawal information RPC endpoint for NFTs (https://github.com/hirosystems/stacks-subnets/pull/131) and for STX (https://github.com/hirosystems/stacks-subnets/pull/116). 

We need to implement a similar endpoint for fungible tokens.

**Comment by obycode** [comment]
This can be closed with #218.
