### ISSUE TITLE
Refactor subnets.clar once new Clarity2 trait features are merged

### ISSUE THREAD

**Issue by pavitthrap** [hirosystems/stacks-subnets#165]
With the change in traits in Clarity in this PR (https://github.com/stacks-network/stacks-blockchain/pull/3269), traits will be a distinct type in Clarity. Thus, with this change, it will be possible for an argument to a function to have the type `(optional trait)`. 

We can use this to refactor the withdraw-nft / withdraw-ft functions. These functions currently have two variants, one variant takes in a separate mint trait, and the other version does not take in this mint trait. We can combine these variants into one, and take in the mint trait as an `(optional trait)`.

**Comment by saralab** [comment]
@gregorycoppola - Related next step to the Clarity2 merge .

**Comment by gregorycoppola** [comment]
fixed by #181
