### ISSUE TITLE
Problem with issue automation

### ISSUE THREAD

**Issue by obycode** [hirosystems/stacks-subnets#197]
https://github.com/hirosystems/stacks-subnets/actions/runs/3879543000

**Comment by aravindgee** [comment]
Related to [Issue #1033](https://github.com/hirosystems/devops/issues/1033) - to address this, [project has been migrated](https://github.com/orgs/hirosystems/projects/24/views/1) to the new layout, which supports automation/actions. Closing this issue has duplicate, will continue to track over at the earlier issue.
