### ISSUE TITLE
Use `withdrawal-id` instead of `withdrawal_id` in events

### ISSUE THREAD

**Issue by obycode** [hirosystems/stacks-subnets#245]
There is an inconsistency in the naming of `withdrawal_id`. Since other event data is coming from Clarity, the standard is to use kebab-case. The withdrawal event should be updated to follow this standard. 

Note that this will require a synchronized change with the API.

**Comment by zone117x** [comment]
This particular event property isn't being explicitly extracted in the API codebase right now. So feel free to make this change without worrying about breakage on the API-side 👍
