### ISSUE TITLE
Use microblock state in read-only calls

### ISSUE THREAD

**Issue by obycode** [hirosystems/stacks-subnets#298]
Read-only calls in a subnet should report state from unconfirmed microblocks, since they are considered reliable.

**Comment by obycode** [comment]
This also includes map and data var lookups.

**Comment by jbencin** [comment]
It's already possible to get microblock state for any API call if you include `latest` in the query string, but I can change this to be the default

**Comment by obycode** [comment]
Oh, that's awesome! Yeah, making that the default sounds good. Thanks
