### ISSUE TITLE
Disabling L2 forks

### ISSUE THREAD

**Issue by kantai** [hirosystems/stacks-subnets#66]
The implementation of the hyperchain-node currently uses the same logic as the current stacks-node to choose what tip to mine from: it reads the current canonical tip (based on what the last L1 block committed) and builds off of that. However, because in hyperchains, the miner always “wins” their blocks, the miner should always build their next block off of the previous block (once it has been confirmed). In practice, this is already the case: because no other miner could be getting confirmed, the hyperchain-node will always be building off of its previous block, however, we should add explicit checks to the codebase that ensures this is actually true.

**Comment by gregorycoppola** [comment]
What are the "explicit checks"? I'm guessing we will check that a block at height `h+1` must build off of a block at height `h`. However, what else are we checking?

What will happen if the miner at height `h+1` does not have any block at height `h`? Does it block until that time?

What if the block at height `h` never reaches the miner for `h+1`? Will it stall forever? Or, how will it recover?

**Comment by kantai** [comment]
The miner should track the height of the last block it committed, and then it should only build a block that is that height +1.

**Comment by gregorycoppola** [comment]
I recall we decided the L2 miner was already not forking.
