### ISSUE TITLE
Use `next` (Stacks 2.1) branch for L1 integration tests and Clarinet tests

### ISSUE THREAD

**Issue by kantai** [hirosystems/stacks-subnets#96]
We should use the new features of Stacks 2.1 in `next` in our prototype hyperchains contract -- in particular, the `from-consensus` and `to-consensus-buff` functions would be immensely useful for withdrawals.

**Comment by pavitthrap** [comment]
Now, block height of the withdrawal is being used to generate the withdrawal keys, so this needs to be passed into the withdrawal methods as well.
